### ISSUE TITLE
Doc NextMN Lite - update PDU session estab.

### ISSUE THREAD

**Issue by elavinal** [nextmn/testbed#84]
Pourrais-tu stp ajouter dans le diag de séquence "PDU Session Establishment procedure" les deux process SRGW et Anchor ?
(en considérant un seul service)

C'est juste pour avoir les deux règles initiales qui sont poussées par le contrôleur (une uplink sur SRGW et une downlink sur Anchor). Et à partir de là on peut présenter les scénarios de handover.

**Comment by louisroyer** [comment]
https://github.com/nextmn/testbed/blob/doc/doc/nextmn-lite.md

**Comment by elavinal** [comment]
Les "create rule" partent du CP ou du SRv6Ctrl ?

**Comment by louisroyer** [comment]
oups… du SRv6Ctrl

**Comment by elavinal** [comment]
Great 👍
